version: "3"

services:
  insightsdb:
    image: mysql:5.7
    ports:
      - '3306:3306'
    volumes:
      - ./data/insightsdb:/data/insightsdb
    environment:
      - MYSQL_CONNECTION=mysql
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  phpmyadminapp:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - insightsdb
    ports:
      - '83:80'
    volumes:
      - ./:/home/node/thera-phpmyadminapp
    environment:
      - PMA_ARBITRARY=1
